name: Pull Requests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: actions/setup-node@56899e050abffc08c2b3b61f3ec6a79a9dc3223d
        with:
          node-version: 12

      - uses: actions/cache@0781355a23dac32fd3bac414512f4b903437991a
        id: cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        # if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline
      - run: npm run test-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
